import type {
  IncomingMessage,
  OutgoingHttpHeaders,
  ServerResponse,
} from "node:http";
import { Writable, type Transform } from "node:stream";
import zlib from "node:zlib";

export type CompressionAlgorithm = "br" | "gzip" | "deflate" | "identity";

export interface CompressionOptions {
  /**
   * Compression algorithms ordered by server preference.
   *
   * Default:
   * ["br", "gzip", "deflate"]
   */
  algorithms?: CompressionAlgorithm[];

  /**
   * Minimum response size in bytes required
   * before compression is enabled.
   *
   * Default: 1024
   */
  threshold?: number;

  /**
   * MIME types eligible for compression.
   */
  mimeTypes?: (string | RegExp)[];

  /**
   * Compression levels.
   */
  levels?: {
    br?: number;
    gzip?: number;
    deflate?: number;
  };

  /**
   * Disable compression for responses containing
   * sensitive headers.
   *
   * Defense-in-depth against BREACH-style attacks.
   */
  enableBreachMitigation?: boolean;

  /**
   * Headers that prevent compression.
   */
  sensitiveHeaders?: string[];

  /**
   * Application-level compression filter.
   */
  shouldCompress?: (req: IncomingMessage, res: ServerResponse) => boolean;
}

export interface NegotiatedEncoding {
  algorithm: CompressionAlgorithm;
  qValue: number;
  acceptable: boolean;
}

type CompressionState = "pending" | "identity" | "compressing" | "rejected";

const DEFAULT_MIME_TYPES: (string | RegExp)[] = [
  /^text\/.+$/i,
  /^application\/json$/i,
  /^application\/javascript$/i,
  /^application\/xml$/i,
  /^application\/wasm$/i,
  /^image\/svg\+xml$/i,
];

const NO_BODY_STATUS_CODES = new Set<number>([204, 304]);

/**
 * Convert a value into a safe byte length.
 *
 * Used for res.end(chunk) where Content-Length
 * has not yet been generated by Node.
 */
function getChunkByteLength(
  chunk: unknown,
  encoding?: BufferEncoding,
): number | undefined {
  if (chunk === undefined) {
    return 0;
  }

  if (typeof chunk === "string") {
    return Buffer.byteLength(chunk, encoding);
  }

  if (Buffer.isBuffer(chunk)) {
    return chunk.byteLength;
  }

  if (chunk instanceof Uint8Array) {
    return chunk.byteLength;
  }

  /*
   * Node's ServerResponse expects string,
   * Buffer, or Uint8Array for body data.
   */
  return undefined;
}

function clampInteger(
  value: number,
  min: number,
  max: number,
  fallback: number,
): number {
  if (!Number.isFinite(value)) {
    return fallback;
  }

  return Math.min(max, Math.max(min, Math.trunc(value)));
}

/**
 * Parse an HTTP q-value.
 *
 * Valid:
 *
 * 0
 * 0.5
 * 0.500
 * 1
 * 1.0
 *
 * Invalid:
 *
 * 1.1
 * 0.1234
 * abc
 */
function parseQValue(value: string): number | null {
  const normalized = value.trim();

  if (!normalized) {
    return null;
  }

  const parsed = Number(normalized);

  if (!Number.isFinite(parsed) || parsed < 0 || parsed > 1) {
    return null;
  }

  const decimalIndex = normalized.indexOf(".");

  if (decimalIndex !== -1) {
    const decimalPlaces = normalized.length - decimalIndex - 1;

    if (decimalPlaces > 3) {
      return null;
    }
  }

  return parsed;
}

function normalizeMimeType(value: string): string {
  return value.split(";", 1)[0]?.trim().toLowerCase() ?? "";
}

function getHeaderString(
  res: ServerResponse,
  name: string,
): string | undefined {
  const value = res.getHeader(name);

  if (typeof value === "string") {
    return value;
  }

  if (typeof value === "number") {
    return String(value);
  }

  if (Array.isArray(value)) {
    return value.map(String).join(", ");
  }

  return undefined;
}

function isBodylessResponse(
  req: IncomingMessage,
  res: ServerResponse,
): boolean {
  if (req.method?.toUpperCase() === "HEAD") {
    return true;
  }

  const status = res.statusCode;

  if (status >= 100 && status < 200) {
    return true;
  }

  return NO_BODY_STATUS_CODES.has(status);
}

/**
 * Adds Accept-Encoding to Vary without
 * creating duplicates.
 */
function addVaryAcceptEncoding(res: ServerResponse): void {
  const existing = res.getHeader("Vary");

  if (existing === undefined) {
    res.setHeader("Vary", "Accept-Encoding");

    return;
  }

  if (existing === "*") {
    return;
  }

  const values: string[] = Array.isArray(existing)
    ? existing.flatMap((value) =>
        String(value)
          .split(",")
          .map((item) => item.trim())
          .filter(Boolean),
      )
    : String(existing)
        .split(",")
        .map((item) => item.trim())
        .filter(Boolean);

  const exists = values.some(
    (value) => value.toLowerCase() === "accept-encoding",
  );

  if (!exists) {
    values.push("Accept-Encoding");
  }

  res.setHeader("Vary", values.join(", "));
}

export class SubatomCompression {
  private readonly opts: {
    algorithms: CompressionAlgorithm[];
    threshold: number;
    mimeTypes: (string | RegExp)[];
    levels: {
      br: number;
      gzip: number;
      deflate: number;
    };
    enableBreachMitigation: boolean;
    sensitiveHeaders: string[];
    shouldCompress?: CompressionOptions["shouldCompress"];
  };

  constructor(options: CompressionOptions = {}) {
    this.opts = {
      algorithms: [...(options.algorithms ?? ["br", "gzip", "deflate"])],

      threshold: Math.max(
        0,
        Number.isFinite(options.threshold ?? 1024)
          ? (options.threshold ?? 1024)
          : 1024,
      ),

      mimeTypes: options.mimeTypes ?? DEFAULT_MIME_TYPES,

      levels: {
        br: clampInteger(options.levels?.br ?? 4, 0, 11, 4),

        gzip: clampInteger(
          options.levels?.gzip ?? zlib.constants.Z_DEFAULT_COMPRESSION,
          -1,
          9,
          zlib.constants.Z_DEFAULT_COMPRESSION,
        ),

        deflate: clampInteger(
          options.levels?.deflate ?? zlib.constants.Z_DEFAULT_COMPRESSION,
          -1,
          9,
          zlib.constants.Z_DEFAULT_COMPRESSION,
        ),
      },

      enableBreachMitigation: options.enableBreachMitigation ?? true,

      sensitiveHeaders: (
        options.sensitiveHeaders ?? ["set-cookie", "x-csrf-token"]
      ).map((header) => header.trim().toLowerCase()),

      shouldCompress: options.shouldCompress,
    };
  }

  /**
   * Negotiate the best response encoding.
   */
  public negotiate(
    acceptEncodingHeader: string | undefined,
  ): NegotiatedEncoding {
    /*
     * No Accept-Encoding header.
     *
     * The client did not restrict encodings.
     * Use server preference.
     */
    if (acceptEncodingHeader === undefined) {
      const preferred = this.opts.algorithms.find(
        (algorithm) => algorithm !== "identity",
      );

      if (preferred) {
        return {
          algorithm: preferred,
          qValue: 1,
          acceptable: true,
        };
      }

      return {
        algorithm: "identity",
        qValue: 1,
        acceptable: true,
      };
    }

    /*
     * Explicit empty header.
     */
    if (acceptEncodingHeader.trim() === "") {
      return {
        algorithm: "identity",
        qValue: 1,
        acceptable: true,
      };
    }

    const preferences = new Map<string, number>();

    for (const rawEntry of acceptEncodingHeader.split(",")) {
      const entry = rawEntry.trim();

      if (!entry) {
        continue;
      }

      const parts = entry.split(";");

      const encoding = parts[0]?.trim().toLowerCase();

      if (!encoding) {
        continue;
      }

      let q = 1;

      for (let i = 1; i < parts.length; i++) {
        const parameter = parts[i]?.trim();

        if (!parameter) {
          continue;
        }

        const separator = parameter.indexOf("=");

        if (separator === -1) {
          continue;
        }

        const name = parameter.slice(0, separator).trim().toLowerCase();

        if (name !== "q") {
          continue;
        }

        const rawQ = parameter.slice(separator + 1).trim();

        q = parseQValue(rawQ) ?? 0;

        break;
      }

      const previous = preferences.get(encoding);

      if (previous === undefined || q > previous) {
        preferences.set(encoding, q);
      }
    }

    const wildcardQ = preferences.get("*");

    const hasExplicitIdentity = preferences.has("identity");

    const identityQ = hasExplicitIdentity
      ? (preferences.get("identity") ?? 0)
      : wildcardQ === 0
        ? 0
        : 1;

    const getEncodingQ = (algorithm: CompressionAlgorithm): number => {
      /*
       * Explicit encoding always wins
       * over wildcard.
       */
      const explicit = preferences.get(algorithm);

      if (explicit !== undefined) {
        return explicit;
      }

      if (wildcardQ !== undefined) {
        return wildcardQ;
      }

      return 0;
    };

    let bestCompression: CompressionAlgorithm | undefined;

    let bestCompressionQ = 0;

    /*
     * Iterate in server preference order.
     *
     * Only a strictly higher q-value replaces
     * the current selection.
     */
    for (const algorithm of this.opts.algorithms) {
      if (algorithm === "identity") {
        continue;
      }

      const q = getEncodingQ(algorithm);

      if (q > 0 && q > bestCompressionQ) {
        bestCompression = algorithm;

        bestCompressionQ = q;
      }
    }

    /*
     * Compression is available.
     */
    if (bestCompression) {
      /*
       * Explicit identity wins only when
       * its q-value is greater than compression.
       *
       * Equal q-values prefer compression.
       */
      if (hasExplicitIdentity && identityQ > bestCompressionQ) {
        return {
          algorithm: "identity",
          qValue: identityQ,
          acceptable: identityQ > 0,
        };
      }

      return {
        algorithm: bestCompression,
        qValue: bestCompressionQ,
        acceptable: true,
      };
    }

    /*
     * No compression available.
     *
     * Identity is the fallback representation
     * unless explicitly forbidden.
     */
    if (identityQ > 0) {
      return {
        algorithm: "identity",
        qValue: identityQ,
        acceptable: true,
      };
    }

    /*
     * Nothing is acceptable.
     */
    return {
      algorithm: "identity",
      qValue: 0,
      acceptable: false,
    };
  }

  /**
   * Determines whether a response is eligible
   * for compression.
   *
   * `knownLength` is optional and is used when
   * res.end(body) provides a body before Node
   * has generated Content-Length.
   */
  public isCompressible(
    req: IncomingMessage,
    res: ServerResponse,
    knownLength?: number,
  ): boolean {
    if (this.opts.shouldCompress && !this.opts.shouldCompress(req, res)) {
      return false;
    }

    /*
     * Never double encode.
     */
    if (res.getHeader("content-encoding") !== undefined) {
      return false;
    }

    /*
     * No-body responses.
     */
    if (isBodylessResponse(req, res)) {
      return false;
    }

    /*
     * BREACH mitigation.
     */
    if (this.opts.enableBreachMitigation) {
      for (const headerName of this.opts.sensitiveHeaders) {
        if (res.getHeader(headerName) !== undefined) {
          return false;
        }
      }
    }

    /*
     * Content-Type is required.
     */
    const contentType = getHeaderString(res, "content-type");

    if (!contentType) {
      return false;
    }

    const pureType = normalizeMimeType(contentType);

    if (!pureType) {
      return false;
    }

    const matches = this.opts.mimeTypes.some((pattern) => {
      if (typeof pattern === "string") {
        return pattern.trim().toLowerCase() === pureType;
      }

      /*
       * Prevent global/sticky regex state
       * from affecting future requests.
       */
      pattern.lastIndex = 0;

      return pattern.test(pureType);
    });

    if (!matches) {
      return false;
    }

    /*
     * Content-Length is authoritative
     * when available.
     */
    const contentLength = res.getHeader("content-length");

    if (contentLength !== undefined) {
      const length =
        typeof contentLength === "number"
          ? contentLength
          : Number(contentLength);

      if (!Number.isFinite(length) || length < 0) {
        return false;
      }

      return length >= this.opts.threshold;
    }

    /*
     * res.end(body) can provide a body size
     * before Content-Length exists.
     */
    if (knownLength !== undefined) {
      return knownLength >= this.opts.threshold;
    }

    /*
     * No known length.
     *
     * Streaming responses are allowed.
     */
    return true;
  }

  /**
   * Creates a compressor stream.
   */
  public createCompressorStream(
    algorithm: CompressionAlgorithm,
  ): Transform | null {
    try {
      switch (algorithm) {
        case "br":
          return zlib.createBrotliCompress({
            params: {
              [zlib.constants.BROTLI_PARAM_QUALITY]: this.opts.levels.br,
            },
          });

        case "gzip":
          return zlib.createGzip({
            level: this.opts.levels.gzip,
          });

        case "deflate":
          return zlib.createDeflate({
            level: this.opts.levels.deflate,
          });

        case "identity":
        default:
          return null;
      }
    } catch {
      return null;
    }
  }

  /**
   * Compression middleware.
   */
  public middleware() {
    return (
      req: IncomingMessage,
      res: ServerResponse,
      next: (err?: unknown) => void,
    ): void => {
      /*
       * Save original ServerResponse methods.
       */
      const originalWrite = res.write.bind(res);

      const originalEnd = res.end.bind(res);

      const originalWriteHead = res.writeHead.bind(res);

      const originalFlushHeaders = res.flushHeaders.bind(res);

      let state: CompressionState = "pending";

      let compressor: Transform | null = null;

      let responseSink: Writable | null = null;

      let rejectionPending = false;

      let closeHandler: (() => void) | null = null;

      const cleanup = (): void => {
        if (closeHandler) {
          res.removeListener("close", closeHandler);

          closeHandler = null;
        }
      };

      /**
       * Writable destination for compressor.
       *
       * IMPORTANT:
       *
       * It calls originalWrite/originalEnd,
       * not patched res.write/res.end.
       *
       * This prevents recursion.
       */
      const createResponseSink = (): Writable => {
        return new Writable({
          write(chunk, _encoding, callback) {
            if (res.destroyed || res.writableEnded) {
              callback(new Error("HTTP response is no longer writable"));

              return;
            }

            let canContinue = false;

            try {
              canContinue = originalWrite(chunk);
            } catch (error) {
              callback(
                error instanceof Error ? error : new Error(String(error)),
              );

              return;
            }

            if (canContinue) {
              callback();
              return;
            }

            /*
             * Backpressure.
             */
            res.once("drain", callback);
          },

          final(callback) {
            if (res.destroyed || res.writableEnded) {
              callback();
              return;
            }

            try {
              originalEnd();
              callback();
            } catch (error) {
              callback(
                error instanceof Error ? error : new Error(String(error)),
              );
            }
          },

          destroy(error, callback) {
            if (error && !res.destroyed) {
              res.destroy(error);
            }

            callback(error ?? undefined);
          },
        });
      };

      /**
       * Initialize compression.
       *
       * knownLength is important for:
       *
       * res.end("small body")
       *
       * when Content-Length has not yet
       * been generated.
       */
      const initialize = (
        statusCode?: number,
        knownLength?: number,
      ): "compressing" | "identity" | "rejected" => {
        if (state === "compressing") {
          return "compressing";
        }

        if (state === "identity") {
          return "identity";
        }

        if (state === "rejected") {
          return "rejected";
        }

        if (statusCode !== undefined) {
          res.statusCode = statusCode;
        }

        /*
         * Once headers are already sent,
         * compression can no longer be enabled.
         */
        if (res.headersSent) {
          state = "identity";
          return "identity";
        }

        /*
         * HEAD/204/304/etc.
         */
        if (isBodylessResponse(req, res)) {
          state = "identity";
          return "identity";
        }

        /*
         * Do not double encode.
         */
        if (res.getHeader("content-encoding") !== undefined) {
          state = "identity";
          return "identity";
        }

        const acceptEncoding = req.headers["accept-encoding"];

        const negotiation = this.negotiate(
          typeof acceptEncoding === "string" ? acceptEncoding : undefined,
        );

        /*
         * Nothing acceptable.
         *
         * IMPORTANT:
         *
         * Do NOT call originalEnd() here.
         *
         * The application may still execute
         * res.end() after middleware initialization.
         *
         * We mark rejectionPending and allow the
         * patched res.end() to perform the actual
         * response termination.
         */
        if (!negotiation.acceptable) {
          state = "rejected";

          rejectionPending = true;

          addVaryAcceptEncoding(res);

          res.statusCode = 406;

          res.setHeader("Content-Type", "text/plain; charset=utf-8");

          res.removeHeader("Content-Length");

          return "rejected";
        }

        /*
         * Check response eligibility.
         */
        if (!this.isCompressible(req, res, knownLength)) {
          state = "identity";
          return "identity";
        }

        /*
         * Add Vary before headers are committed.
         */
        addVaryAcceptEncoding(res);

        /*
         * Client selected identity.
         */
        if (negotiation.algorithm === "identity") {
          state = "identity";
          return "identity";
        }

        /*
         * Create zlib stream.
         */
        const created = this.createCompressorStream(negotiation.algorithm);

        if (!created) {
          state = "identity";
          return "identity";
        }

        compressor = created;

        /*
         * Original Content-Length belongs
         * to the uncompressed representation.
         */
        res.removeHeader("Content-Length");

        res.setHeader("Content-Encoding", negotiation.algorithm);

        responseSink = createResponseSink();

        closeHandler = () => {
          if (compressor && !compressor.destroyed) {
            compressor.destroy();
          }

          if (responseSink && !responseSink.destroyed) {
            responseSink.destroy();
          }

          cleanup();
        };

        res.once("close", closeHandler);

        compressor.once("error", (error) => {
          cleanup();

          if (!res.destroyed) {
            res.destroy(error);
          }
        });

        responseSink.once("error", (error) => {
          cleanup();

          if (!res.destroyed) {
            res.destroy(error);
          }
        });

        /*
         * Compressor output goes directly
         * to original ServerResponse.
         */
        compressor.pipe(responseSink);

        state = "compressing";

        return "compressing";
      };

      const copyHeaders = (headers: OutgoingHttpHeaders): void => {
        for (const [name, value] of Object.entries(headers)) {
          if (value === undefined) {
            continue;
          }

          res.setHeader(name, value);
        }
      };

      /**
       * ------------------------------------------------------------------
       * writeHead()
       * ------------------------------------------------------------------
       */
      res.writeHead = function (
        this: ServerResponse,
        statusCode: number,
        statusMessageOrHeaders?: string | OutgoingHttpHeaders,
        headers?: OutgoingHttpHeaders,
      ): ServerResponse {
        if (
          statusMessageOrHeaders &&
          typeof statusMessageOrHeaders !== "string"
        ) {
          copyHeaders(statusMessageOrHeaders);
        }

        if (headers !== undefined) {
          copyHeaders(headers);
        }

        const result = initialize(statusCode);

        if (result === "rejected") {
          return originalWriteHead(statusCode);
        }

        if (typeof statusMessageOrHeaders === "string") {
          return originalWriteHead(statusCode, statusMessageOrHeaders);
        }

        return originalWriteHead(statusCode);
      } as ServerResponse["writeHead"];
      /**
       * ------------------------------------------------------------------
       * flushHeaders()
       * ------------------------------------------------------------------
       */
      res.flushHeaders = function (this: ServerResponse): void {
        const result = initialize();

        if (result === "rejected") {
          /*
           * Emit the 406 headers now.
           * Body will be sent through res.end().
           */
          originalFlushHeaders();
          return;
        }

        originalFlushHeaders();
      };

      /**
       * ------------------------------------------------------------------
       * write()
       * ------------------------------------------------------------------
       */
      res.write = function (
        this: ServerResponse,
        chunk: any,
        encodingOrCallback?: BufferEncoding | ((error?: Error | null) => void),
        callback?: (error?: Error | null) => void,
      ): boolean {
        const result = initialize();

        /*
         * A rejected response must not accept
         * application body writes.
         *
         * The actual 406 body is generated
         * by res.end().
         */
        if (result === "rejected") {
          const error = new Error(
            "Response was rejected by Accept-Encoding negotiation",
          );

          if (typeof encodingOrCallback === "function") {
            encodingOrCallback(error);
          } else if (callback) {
            callback(error);
          }

          return false;
        }

        /*
         * Compressed response.
         */
        if (result === "compressing" && compressor) {
          if (typeof encodingOrCallback === "function") {
            return compressor.write(chunk, encodingOrCallback);
          }

          if (encodingOrCallback !== undefined) {
            return compressor.write(chunk, encodingOrCallback, callback);
          }

          if (callback) {
            return compressor.write(chunk, callback);
          }

          return compressor.write(chunk);
        }

        /*
         * Identity response.
         */
        if (typeof encodingOrCallback === "function") {
          return originalWrite(chunk, encodingOrCallback);
        }

        if (encodingOrCallback !== undefined) {
          return originalWrite(chunk, encodingOrCallback, callback);
        }

        if (callback) {
          return originalWrite(chunk, callback);
        }

        return originalWrite(chunk);
      } as ServerResponse["write"];

      /**
       * ------------------------------------------------------------------
       * end()
       * ------------------------------------------------------------------
       */
      res.end = function (
        this: ServerResponse,
        chunk?: any,
        encodingOrCallback?: BufferEncoding | (() => void),
        callback?: () => void,
      ): ServerResponse {
        /*
         * Determine final body size if possible.
         */
        let knownLength: number | undefined;

        if (chunk !== undefined && typeof chunk !== "function") {
          const encoding =
            typeof encodingOrCallback === "string"
              ? encodingOrCallback
              : undefined;

          knownLength = getChunkByteLength(chunk, encoding);
        }

        const result = initialize(undefined, knownLength);

        /*
         * 406 negotiation rejection.
         *
         * This is where the actual response is
         * terminated.
         *
         * This fixes the malformed HTTP response
         * produced by ending it too early in initialize().
         */
        if (result === "rejected") {
          rejectionPending = false;

          try {
            return originalEnd("Not Acceptable");
          } catch {
            if (!res.destroyed) {
              res.destroy();
            }

            return res;
          }
        }

        /*
         * Compression path.
         */
        if (result === "compressing" && compressor) {
          if (chunk !== undefined && typeof chunk !== "function") {
            if (typeof encodingOrCallback === "string") {
              compressor.end(chunk, encodingOrCallback, callback);

              return res;
            }

            if (typeof encodingOrCallback === "function") {
              compressor.end(chunk, encodingOrCallback);

              return res;
            }

            if (callback) {
              compressor.end(chunk, callback);

              return res;
            }

            compressor.end(chunk);

            return res;
          }

          if (typeof chunk === "function") {
            compressor.end(chunk);

            return res;
          }

          if (typeof encodingOrCallback === "function") {
            compressor.end(encodingOrCallback);

            return res;
          }

          if (callback) {
            compressor.end(callback);

            return res;
          }

          compressor.end();

          return res;
        }

        /*
         * Identity response.
         */
        if (chunk === undefined) {
          if (typeof encodingOrCallback === "function") {
            return originalEnd(encodingOrCallback);
          }

          if (callback) {
            return originalEnd(callback);
          }

          return originalEnd();
        }

        if (typeof chunk === "function") {
          return originalEnd(chunk);
        }

        if (typeof encodingOrCallback === "string") {
          return originalEnd(chunk, encodingOrCallback, callback);
        }

        if (typeof encodingOrCallback === "function") {
          return originalEnd(chunk, encodingOrCallback);
        }

        if (callback) {
          return originalEnd(chunk, callback);
        }

        return originalEnd(chunk);
      } as ServerResponse["end"];

      /*
       * Compression is initialized lazily.
       *
       * This allows the route/controller to set:
       *
       * Content-Type
       * Content-Length
       * Set-Cookie
       * etc.
       *
       * before compression negotiation happens.
       */
      next();
    };
  }
}

export function createCompression(options?: CompressionOptions) {
  const engine = new SubatomCompression(options);

  return engine.middleware();
}
